alias: Video Fortschritt 95%
description: ""
trigger:
  - platform: state
    entity_id:
      - media_player.shield
condition: []
action:
  - variables:
      ninety_five_percent_time: >
        {% set duration = state_attr('media_player.SHIELD', 'media_duration') | float %}
        {% set position = state_attr('media_player.SHIELD','media_position') | float %}
        {% set updated_at = state_attr('media_player.SHIELD','media_position_updated_at') %}
        {% if duration > 0 and position is defined and updated_at is defined %}
          {{ (updated_at.timestamp() + (duration * 0.95)) }}
        {% endif %}
      stop_at: >
        {% if ninety_five_percent_time is defined %}

        {% set position = state_attr('media_player.SHIELD','media_position') | float %}
          {{ ninety_five_percent_time - position if position is defined else ninety_five_percent_time }}
        {% endif %}
  - condition: template
    value_template: "{{ as_timestamp(now()) <= stop_at if stop_at is defined else false }}"
  - repeat:
      sequence:
        - delay:
            hours: 0
            minutes: 0
            seconds: 1
            milliseconds: 0
      until:
        - condition: template
          value_template: >-
            {{ as_timestamp(now()) >= stop_at if stop_at is defined else false }}
  - condition: state
    entity_id: media_player.shield
    state: playing
  - service: scene.turn_on
    target:
      entity_id: scene.kino_abspann
    metadata: {}
mode: restart
